site_name: pyochain
theme:
  name: material

plugins:
  - search
  - autorefs
  - mermaid2:
      version: 10.4.0
      arguments:
        securityLevel: 'loose'
      default_handler: python
      handlers:
        python:
          paths: ["src"]
          options:
            members_order: source
            inherited_members: true
            show_signature_annotations: true
            separate_signature: true
            line_length: 88
            docstring_style: google
            show_if_no_docstring: true
            show_source: true
            show_overloads: true
            filters:
              - "!^_"
nav:
  - Home: index.md
  - Getting Started:
      - Core Types Overview: core-types-overview.md
      - Examples & Cookbook: examples.md
  - API Reference:
      - Collections:
          - Iter: reference/iter.md
          - Seq: reference/seq.md
          - Vec: reference/vec.md
          - Set: reference/set.md
          - SetMut: reference/setmut.md
          - Dict: reference/dict.md
      - Error Handling:
          - Result: reference/result.md
          - Ok: reference/ok.md
          - Err: reference/err.md
      - Optional Values:
          - Option: reference/option.md
          - Some: reference/some.md
          - None: reference/none.md
  

theme:
  name: material
  palette:
    - scheme: slate         # dark
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default       # light
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Passer en mode sombre
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: false
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.details
