site_name: pyochain
theme:
  name: material

plugins:
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["src"]
          options:
            members_order: source
            inherited_members: true
            show_signature_annotations: true
            separate_signature: true
            line_length: 88
            docstring_style: google
            show_if_no_docstring: true
            show_source: true
            show_overloads: true
            filters:
              - "!^_"
nav:
  - Home: index.md
  - Guides:
      - Overview: guides/index.md
      - Chaining Methods: guides/chaining.md
  - Reference:
      - Iter: reference/iter.md
      - Dict: reference/dict.md
      - Seq: reference/seq.md
      - Set: reference/set.md
      - Vec: reference/vec.md
      - Result: reference/result.md
      - Option: reference/option.md
      - Ok: reference/ok.md
      - Err: reference/err.md
      - Some: reference/some.md
      - None: reference/none.md
  

theme:
  name: material
  palette:
    - scheme: slate         # dark
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default       # light
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Passer en mode sombre
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: false
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.details
